# values.yaml
replicaCount: 2

namespace: "custom-namespace"

image:
  repository: shashank30mishra/boardgame
  tag: latest
  pullPolicy: Always

service:
  name: boardgame-ssvc
  port: 8080
  type: LoadBalancer

resources: {}

serviceAccount:
  name: ""  # Set to override the default (e.g., pr-generator-sa)

secretName: github-token-secret
