apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-reader-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}  # ServiceAccount name passed from values.yaml
    namespace: preview
roleRef:
  kind: ClusterRole
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
