apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-comment
  namespace: preview
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "boardgame.serviceAccountName" . }}
      containers:
      - name: comment-pr
        image: djieno/alpine-curl-kubectl:amd64
        command:
          - /bin/sh
          - -c
          - |
            sleep 500
            SERVICE_URL=$(kubectl get svc -n pr-$PR_NUMBER -o jsonpath='{.items[?(@.status.loadBalancer.ingress[0].ip)].status.loadBalancer.ingress[0].ip}' )

            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/$GITHUB_REPO/issues/$PR_NUMBER/comments \
                 -d "{\"body\": \"✅ Sync Completed! 🎉\n\nService is available at: [http://$SERVICE_URL:8080](http://$SERVICE_URL:8080)\"}" > /dev/null 2>&1
                 echo "PR comment is completed"
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token-secret
                key: key
          - name: GITHUB_REPO
            value: "{{ .Values.repoName }}"  # Change to your GitHub repo
          - name: PR_NUMBER
            value: "{{ .Values.prNumber }}"
      restartPolicy: Never



