apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}


---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: ingress-reader
#   namespace: {{ .Release.Namespace }}
# rules:
#   - apiGroups: ["networking.k8s.io"]
#     resources: ["ingresses"]
#     verbs: ["get", "list"]
#   - apiGroups: [""]
#     resources: ["services"]
#     verbs: ["get", "list"]



# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: ingress-reader-binding
#   namespace: {{ .Release.Namespace }}
# subjects:
#   - kind: ServiceAccount
#     name: {{ include "boardgame.serviceAccountName" . }}
#     namespace: {{ .Release.Namespace }}
# roleRef:
#   kind: Role
#   name: ingress-reader
#   apiGroup: rbac.authorization.k8s.io

