# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
